config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :pets do
    resources :treatments, only: %i[new create]
    resources :appointments, only: %i[new create]
    resources :vaccines, only: %i[new create]
    resources :exams, only: %i[new create show]
    resources :dewormings, only: %i[new create]
  end
  resources :treatments, only: %i[edit update destroy]
  resources :appointments, only: %i[edit update destroy]
  resources :vaccines, only: %i[edit update destroy]
  resources :exams, only: %i[edit update destroy]
  resources :dewormings, only: %i[edit update destroy]

  get "/calendar", to: "pages#calendar", as: "calendar"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :treatments, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :vaccines, dependent: :destroy
  has_many :exams, dependent: :destroy
  has_many :dewormings, dependent: :destroy
  has_many :meetings
  has_many_attached :photos
  include PgSearch::Model
  pg_search_scope :pets_search,
  against: %i[ name breed birthday gender weight spayed allergies color chiped specie ],
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = policy_scope(Pet)
    @meetings = Meeting.all
    if params[:query].present?
      @pets = policy_scope(Pet.pets_search(params[:query]))
    else
      @pets = policy_scope(Pet)
    end
    @user_mettings = []
    @meetings.each do |meeting|
      if meeting.pet.user == current_user
        @user_mettings.push(meeting)
      end
    end
    @three_meetings = (@user_mettings.sort_by { |meeting| meeting.start_time }).first(3)

  end

  def show
    @pet = Pet.find(params[:id])
    @treatments = @pet.treatments
    @appointments = @pet.appointments
    @vaccines = @pet.vaccines
    @dewormings = @pet.dewormings
    @exams = @pet.exams
    authorize @pet
  end

  def new
    @pet = Pet.new # Needed to instantiate the form_with
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    authorize @pet
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find(params[:id])
    authorize @pet
  end

  def update
    @pet = Pet.find(params[:id])
    authorize @pet
    @pet.update(pet_params)
    # No need for app/views/pets/update.html.erb
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    authorize @pet
    @pet.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to pets_path, status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :breed, :birthday, :gender, :weight, :spayed, :photos, :allergies, :color, :chiped, :type)
  end
end

app/views/pets/_form.html.erb
<div class="container">
  <%= simple_form_for(pet) do |f| %>
  <%= f.input :name, label:"Nombre",placeholder:"Lucky" %>
  <%= f.input :specie, label:"Especie",placeholder:"Perro" %>
  <%= f.input :breed, label:"Raza",placeholder:"Golden Retriever" %>
  <%= f.input :birthday, label:"Fecha de nacimiento" %>
  <%= f.input :gender, label:"Sexo", collection: %w[Macho Hembra] %>
  <%= f.input :weight, label:"Peso(kg)",placeholder:"25" %>
  <%= f.input :spayed, label:"Esterilizado" %>
  <%= f.input :allergies, label:"Alergias",placeholder:"Dermatitis atópica"%>
  <%= f.input :color, label:"Color",placeholder:"Dorado" %>
  <%= f.input :chiped, label:"¿Tiene chip?"%>
  <%= f.input :photos, label:"Foto", as: :file %>
  <%= f.submit "Agregar mascota", class:"btn btn-outline-success" %>
  <% end %>
</div>

app/views/pets/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="card editar col-12 m-5 p-3 rounded-4">
      <%= render "form", pet: @pet %>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class="container">
  <div class="p-2 text-dark">
    <br>
      <h1 class="mx-4 my-3 nombre-perrito" ><strong>Bienvenido <%= current_user.username %></strong> </h1>
      <h3 class="mx-5 p-4" style="font-weight:bolder;font-size:37px;text-shadow: 0.5px 0.5px 1px black;">Estas son tus mascotas:</h3>
        <div class="row m-5 justify-content-around">
          <% @pets.each do |pet| %>
          <div class="col-3 col-lg-2">
            <div class="mx-auto ">
              <% unless pet.photos.empty? %>
                <div class="d-flex justify-content-center mt-5">
                  <%= link_to pet_path(pet) do %>
                  <%= cl_image_tag pet.photos.first.key,height: 150, width: 150, crop: :fill, class:"rounded-circle img-fluid hover" %>
                  <% end %>
                </div>
                <% else %>
                <div class="d-flex justify-content-center mt-5">
                  <%= link_to pet_path(pet) do %>
                  <%= image_tag asset_path("pet-sin-imagen"),height: 150, width: 150, class:"rounded-circle img-fluid hover" %>
                  <% end %>
                </div>
              <% end %>
            <div class="card-trip-infos mt-2">
              <div>
                <h5 class="card-title text-center"><%= link_to pet.name, pet_path(pet), class: "nav-link",style:"font-size:30px;font-weight:bold;text-shadow: 0.25px 0.25px 0.25px black;" %></h5>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <div class="container text-center mt-4 p-5">
          <%= link_to "Agregar mascota", new_pet_path,class:"btn btn-outline-success",style:"font-size:30px;text-shadow: 0.25px 0.25px 0.25px black;" %>
        </div>
  </div>

  <br>

    <div class="container p-3 my-5 back-meetings">
      <h4 class="p-3" style="color:#F8F3DF;font-size:35px">Recordatorios</h4>
      <div class="row justify-content-around">
          <% @three_meetings.each do |meeting| %>
            <div class="col-3 mx-4 my-2">
              <div class="card carta-recordatorio">
                <div class="card-body">
                  <h5 class="card-title"><%= meeting.name %> para <%= meeting.pet.name %> </h5>
                  <p class="card-text">Próxima aplicación: <br><%= meeting.start_time.strftime("%d-%m-%Y") %></p>
                  <button class="btn btn-outline-success"> <%=   link_to "Ver calendario", calendar_path, style:"text-decoration:none;color:black" %> </button>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
</div>
<%# <i class="fa-regular fa-calendar"</i> %>

app/views/pets/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="infoimagen col-6">
    </div>
    <div class="info col-6 card p-3">
      <%= render "form", pet: @pet %>
    </div>
  </div>
</div>