config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :pets do
    resources :treatments, only: %i[new create]
    resources :appointments, only: %i[new create]
    resources :vaccines, only: %i[new create]
    resources :exams, only: %i[new create show]
    resources :dewormings, only: %i[new create]
  end
  resources :treatments, only: %i[edit update destroy]
  resources :appointments, only: %i[edit update destroy]
  resources :vaccines, only: %i[edit update destroy]
  resources :exams, only: %i[edit update destroy]
  resources :dewormings, only: %i[edit update destroy]

  get "/calendar", to: "pages#calendar", as: "calendar"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class= "container-fluid footer size mt-auto ">
  <div class="col-12">
    <div class="row">
      <div class="col-12">
        <div class="row">
          <div class="sobre col-12 mt-5">
            <h3>Sobre Petzone:</h3>
          </div>
          <div class="sobre col-12 my-3">
            <p>El fin de Petzone es organizar una buena calidad de vida para tu mascota a traves de calendarios para vacunas, desparacitaciones y examenes.</p>
          </div>
        </div>
      </div>
      <div class="col-12">
        <div class="row">
          <div class="redes col-12 justify-content-center">
            <h2>Nuestras redes</h2>
          </div>
          <div class="footer-links col-12 justify-content-center">
            <a href="#"><i class="fab fa-github mx-3"></i></a>
            <a href="#"><i class="fab fa-instagram mx-3"></i></a>
            <a href="#"><i class="fab fa-facebook mx-3"></i></a>
            <a href="#"><i class="fab fa-twitter mx-3"></i></a>
            <a href="#"><i class="fab fa-linkedin mx-3"></i></a>
          </div>
          <div class="col-12 justify-content-center">
            <p>Copyright © 2022</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb

<!--New Navbar-->
<nav class="navbar2 d-flex justify-content-between">
  <div class="mt-2 mx-2">

    <!-- Nav Header -->
    <div class="navbar-expand-sm">
      <a class="navbar-brand" href="<%=root_path%>"><span class="fa fa-home"></span><span class="link"> Home</span></a>
      <a class="navbar-brand" href="<%=calendar_path%>"><span class="fa fa-calendar"></span><span class="link"> Calendario</span></a>
      <div class="dropdown d-inline">
        <a class="navbar-brand dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-dog"></span><span class="link">Pets</span></a>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <% current_user.pets.each do |pet| %>
              <li><%= link_to pet.name, pet_path(pet), class: "nav-link"%></li>
            <% end %>
          <% end %>
          <li><%= link_to "Ver todas", pets_path%></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="letter justify-content-center mt-2">
    <h5 class= "letra-nav">Petzone <i class="fa fa-paw"></i></h5>
  </div>
  <div class="letter longs d-flex mt-2 gap-3 strong">
    <% if user_signed_in? %>
      <p><%= current_user.username %></p>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item mx-3" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link m-1" %>
    <% end %>
  </div>
</nav>